name       : sshpass
version    : '1.09'
release    : 2
source     :
    - https://sourceforge.net/projects/sshpass/files/sshpass/1.09/sshpass-1.09.tar.gz/download : 71746e5e057ffe9b00b44ac40453bf47091930cba96bbea8dc48717dedc49fb7
license    : GPL-2.0-only
component  : network.clients
summary    : SSHPass is a tiny utility, which allows you to provide the ssh password without using the prompt.
description: |
    SSHPass is a tiny utility, which allows you to provide the ssh password without using the prompt. - You should use this with caution
rundeps    :
    - openssh
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
