name       : sshpass
version    : 1.06
release    : 1
source     :
    - https://kent.dl.sourceforge.net/project/sshpass/sshpass/1.06/sshpass-1.06.tar.gz : c6324fcee608b99a58f9870157dfa754837f8c48be3df0f5e2f3accf145dee60
license    : GPL-2.0-only
component  : network.clients
summary    : SSHPass is a tiny utility, which allows you to provide the ssh password without using the prompt.
description: |
    SSHPass is a tiny utility, which allows you to provide the ssh password without using the prompt. - You should use this with caution 
rundeps    :
    - openssh
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
